services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app
    command: gradle bootRun

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb_dev
