name: Lint and Typecheck CI

on:
  pull_request:
    branches:
      - main

jobs:
  generate-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache API generation
        id: cache-api
        uses: actions/cache@v4
        with:
          path: ./api/dist
          key: ${{ runner.os }}-api-${{ hashFiles('api/main.tsp') }}
          restore-keys: |
            ${{ runner.os }}-api-
      - name: Generate API files
        if: steps.cache-api.outputs.cache-hit != 'true'
        run: make gen-all
      - name: Upload generated client
        uses: actions/upload-artifact@v4
        with:
          name: generated-client
          path: ./api/dist/client
          retention-days: 1
      - name: Upload generated backend
        uses: actions/upload-artifact@v4
        with:
          name: generated-backend
          path: ./api/dist/server
          retention-days: 1

  lint-backend:
    runs-on: ubuntu-latest
    needs: generate-api
    steps:
      - uses: actions/checkout@v4
      - name: Download generated backend
        uses: actions/download-artifact@v4
        with:
          name: generated-backend
          path: ./api/dist/server
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "23"
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/daemon
            ~/.gradle/native
            backend/.gradle
            backend/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/gradle.properties') }}-${{ hashFiles('backend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/gradle.properties') }}-
            ${{ runner.os }}-gradle-
      - name: Run backend linter
        working-directory: ./backend
        run: make lint

  lint-frontend:
    runs-on: ubuntu-latest
    needs: generate-api
    steps:
      - uses: actions/checkout@v4
      - name: Download generated client
        uses: actions/download-artifact@v4
        with:
          name: generated-client
          path: ./api/dist/client
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: "client/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        working-directory: ./client
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: make install
      - name: Run frontend typecheck
        working-directory: ./client
        run: make typecheck
      - name: Run frontend linter
        working-directory: ./client
        run: make lint
