name: Hotel Booking Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install TypeSpec Compiler
      run: npm install -g @typespec/compiler

    - name: Install OpenAPI Generator
      run: sudo npm install -g @openapitools/openapi-generator-cli

    - name: Generate OpenAPI from TypeSpec
      run: |
        cd backend
        ./generate-openapi.sh

    - name: Generate tests from OpenAPI
      run: |
        cd backend
        ./generate-tests.sh

    - name: Run tests
      run: |
        cd backend/generated-tests
        mvn test 