name: Playwright Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "tests/playwright/package.json"

      - name: Install dependencies
        run: |
          cd tests/playwright
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd tests/playwright
          npx playwright install --with-deps

      - name: Wait for site to be available
        run: |
          chmod +x tests/playwright/wait-for-run-tests.sh
          ./tests/playwright/wait-for-run-tests.sh http://hexling.ru

      - name: Run Playwright tests
        run: |
          cd tests/playwright
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
